import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js';
import { getAuth, onAuthStateChanged, signOut, signInWithEmailAndPassword } from 'https://www.gstatic.com/firebasejs/11.0.2/firebase-auth.js';
import { getFirestore, collection, getDocs, addDoc, updateDoc, deleteDoc, doc, serverTimestamp, enableIndexedDbPersistence } from 'https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyDsoWnSGzzt3BRuL5fIhq7dfg2fqyibM1U',authDomain:'tailor-web-f1f1c.firebaseapp.com',projectId:'tailor-web-f1f1c',storageBucket:'tailor-web-f1f1c.firebasestorage.app',messagingSenderId:'129811668871',appId:'1:129811668871:web:586357e9e696a9652ffd22'};
const app=initializeApp(firebaseConfig); export const auth=getAuth(app); export const db=getFirestore(app);
try{enableIndexedDbPersistence(db).catch(()=>{});}catch(e){}
export {collection,getDocs,addDoc,updateDoc,deleteDoc,doc,serverTimestamp,onAuthStateChanged,signOut,signInWithEmailAndPassword};
export const fields=[['length','لمبائی','Length'],['tera','تیرا','Tera'],['sleeve','آستین','Sleeve'],['neck','گلہ','Neck'],['chest','چھاتی','Chest'],['waist','کمر','Waist'],['daman','دامن','Daman'],['shalwarLength','شلوار لمبائی مکمل','Complete Shalwar Length'],['pancha','پانچہ','Pancha']];
export const designs=[['twoPiece','ٹو پیس','Two Piece'],['band','بین','Band'],['roundDaman','گول دامن','Round Daman'],['squareDaman','چورس دامن','Square Daman'],['bothSides','دوبغل','Both Sides'],['front','سامنے','Front'],['shalwarPocket','شلوار جیب','Shalwar Pocket'],['tilaGoot','تیلا گوٹ','Tila Goot'],['fitCuff','فٹ کف','Fit Cuff'],['simpleSleeve','سادہ آستین','Simple Sleeve'],['cuffed','کف دار','Cuffed']];
export const $=id=>document.getElementById(id);
export const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
export const t=(ur,en)=>localStorage.getItem('lang')==='en'?en:ur;
export function nav(active){const L=localStorage.getItem('lang')==='en';return `<header class="top"><a class="brand" href="index.html">✂️ <span>${L?'Tailor':'درزی'}</span></a><div class="top-actions"><a class="icon-btn" href="search.html" title="${L?'Search':'تلاش'}">🔎</a><button class="icon-btn" id="langBtn">${L?'اردو':'EN'}</button><button class="icon-btn" id="logoutBtn">↪</button></div></header><nav class="nav"><a class="${active==='home'?'active':''}" href="index.html">⌂ <span>${L?'Home':'ہوم'}</span></a><a class="${active==='customers'?'active':''}" href="customers.html">👤 <span>${L?'Customers':'محفوظ کسٹمرز'}</span></a><a class="${active==='new'?'active':''}" href="new-user.html">＋ <span>${L?'New Order':'نیا آرڈر'}</span></a><a class="${active==='pending'?'active':''}" href="pending.html">🧵 <span>${L?'Pending':'پینڈنگ'}</span></a><a class="${active==='complete'?'active':''}" href="completed.html">✓ <span>${L?'Complete':'مکمل'}</span></a></nav>`}
export function bindNav(){ $('langBtn')?.addEventListener('click',()=>{localStorage.setItem('lang',localStorage.getItem('lang')==='en'?'ur':'en');location.reload()}); $('logoutBtn')?.addEventListener('click',()=>signOut(auth).then(()=>location.href='login.html')); }
export function requireAuth(cb){onAuthStateChanged(auth,u=>{if(!u) location.replace('login.html'); else cb(u)});}
