import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js';
import { getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';
import { initializeFirestore,memoryLocalCache,persistentLocalCache,persistentMultipleTabManager,collection,getDocs,addDoc,updateDoc,deleteDoc,doc,serverTimestamp,query,orderBy } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js';
const firebaseConfig={apiKey:'AIzaSyDsoWnSGzzt3BRuL5fIhq7dfg2fqyibM1U',authDomain:'tailor-web-f1f1c.firebaseapp.com',projectId:'tailor-web-f1f1c',storageBucket:'tailor-web-f1f1c.firebasestorage.app',messagingSenderId:'129811668871',appId:'1:129811668871:web:586357e9e696a9652ffd22'};
const app=initializeApp(firebaseConfig); export const auth=getAuth(app);
let db; try{db=initializeFirestore(app,{localCache:persistentLocalCache({tabManager:persistentMultipleTabManager()})})}catch(e){db=initializeFirestore(app,{localCache:memoryLocalCache()})} export {db};
export {onAuthStateChanged,signInWithEmailAndPassword,signOut,collection,getDocs,addDoc,updateDoc,deleteDoc,doc,serverTimestamp,query,orderBy};
export const $=id=>document.getElementById(id); export const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
export const fields=[['length','لمبائی','Length'],['tera','تیرا','Tera'],['sleeve','آستین','Sleeve'],['neck','گلہ','Neck'],['chest','چھاتی','Chest'],['waist','کمر','Waist'],['daman','دامن','Daman'],['shalwarLength','شلوار لمبائی مکمل','Shalwar Length'],['pancha','پانچہ','Pancha']];
export const designs=[['twoPiece','ٹو پیس','Two Piece'],['band','بین','Band'],['roundDaman','گول دامن','Round Daman'],['squareDaman','چورس دامن','Square Daman'],['bothSides','دوبغل','Both Sides'],['front','سامنے','Front'],['shalwarPocket','شلوار جیب','Shalwar Pocket'],['tilaGoot','تیلا گوٹ','Tila Goot'],['fitCuff','فِٹ کف','Fit Cuff'],['simpleSleeve','سادہ آستین','Simple Sleeve'],['cuffed','کف دار','Cuffed']];
export const T={ur:{home:'ہوم',customers:'محفوظ کسٹمرز',new:'نیا آرڈر',pending:'پینڈنگ',complete:'مکمل',logout:'لاگ آؤٹ',saved:'محفوظ کسٹمر',newUser:'نیا یوزر',save:'محفوظ کریں',edit:'ایڈٹ',delete:'ڈیلیٹ',order:'آرڈر',address:'پتہ',area:'علاقہ',phone:'فون نمبر',name:'نام',qty:'کپڑوں کی تعداد',color:'کپڑے کا رنگ',amount:'کل رقم',measurements:'ناپ',design:'ڈیزائن',date:'تاریخ',total:'کل',completed:'مکمل',remaining:'باقی',noData:'ابھی کوئی ریکارڈ نہیں',search:'نام یا فون نمبر تلاش کریں'},en:{home:'Home',customers:'Saved Customers',new:'New Order',pending:'Pending',complete:'Completed',logout:'Logout',saved:'Saved Customer',newUser:'New User',save:'Save',edit:'Edit',delete:'Delete',order:'Order',address:'Address',area:'Area',phone:'Phone',name:'Name',qty:'Clothes Quantity',color:'Cloth Color',amount:'Total Amount',measurements:'Measurements',design:'Design',date:'Date',total:'Total',completed:'Completed',remaining:'Remaining',noData:'No records yet',search:'Search by name or phone'}};
export function getLang(){return localStorage.getItem('tailor_lang')||'ur'} export function setLang(v){localStorage.setItem('tailor_lang',v);location.reload()} export function tr(k){return T[getLang()][k]||k}
export function requireAuth(cb){onAuthStateChanged(auth,u=>u?cb(u):location.replace('login.html'))}
export function nav(active){const l=getLang();return `<header><a class="brand" href="index.html"><span class="brandmark">✂</span><span><b>Tailor</b><small>Simple Manager</small></span></a><nav><a class="${active==='home'?'on':''}" href="index.html">${T[l].home}</a><a class="${active==='customers'?'on':''}" href="customers.html">${T[l].customers}</a><a class="${active==='new'?'on':''}" href="new-user.html">${T[l].new}</a><a class="${active==='pending'?'on':''}" href="pending.html">${T[l].pending}</a><a class="${active==='complete'?'on':''}" href="complete.html">${T[l].complete}</a></nav><div class="header-actions"><button class="lang ${l==='ur'?'on':''}" data-lang="ur">اردو</button><button class="lang ${l==='en'?'on':''}" data-lang="en">English</button><button id="logout" class="iconbtn">↪</button></div></header>`}
export function bindNav(){document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));const x=$('logout');if(x)x.onclick=()=>signOut(auth)}
export function dateText(v){if(!v)return'-';const d=v?.toDate?v.toDate():new Date(v);return isNaN(d)?'-':d.toLocaleDateString(getLang()==='ur'?'ur-PK':'en-PK',{year:'numeric',month:'short',day:'numeric'})}
export function detailsHtml(o){const l=getLang();return `<div class="detail-section"><h3>${T[l].measurements}</h3>${fields.map(([k,u,e])=>`<div class="detail-line"><span>${l==='ur'?u:e}</span><b>${esc(o.measurements?.[k]||'-')}</b></div>`).join('')}</div><div class="detail-section"><h3>${T[l].design}</h3><div class="design-list">${designs.filter(([k])=>o.designs?.[k]).map(([,u,e])=>`<span>${l==='ur'?u:e}</span>`).join('')||'<span>-</span>'}</div></div>`}
